@startuml
mainframe sd: QMS Check-in

box "Frontend"
participant PartnerApp
box end

box "1N Backend"
participant QMS
participant FS
box end

box "DMS Supply"
participant RTS
box end

box "DMS Demand"
participant DevApi
box end

group Approach 1
PartnerApp -> PartnerApp: Scan order
PartnerApp -> FS: /
end

@enduml