@startuml
mainframe sd: Task Creation

box "1N Backend"
participant FS
box end

box "DMS Supply"
participant RTS
box end

box "DMS Demand"
participant DevApi
participant UTS
participant Espresso
box end

FS -> DevApi: /orch/tasks (create)\nreusable-bag enabled\nflag,store-config
activate FS
activate DevApi
DevApi -> UTS: Create MN user task,\nreusable-bag flag
activate UTS
UTS --> DevApi: Created
deactivate UTS
DevApi ->> Espresso: queue_tasks_allocation_async
Espresso ->> RTS: Create runner task (via allocation flow)
activate RTS
RTS -> RTS: create_runner_task(),\nreusable-bag flag
deactivate RTS
note right
Creates runner task in
RTS as per existing flow
via allocation
end note
DevApi --> FS: task_id
deactivate DevApi
deactivate FS

@enduml